name: RedSkyBlock
author: RedCraftPE
version: 0.0.1
api: 3.0.0, 4.0.0
main: RedCraftPE\SkyBlock
commands:
  island:
    description: This is the main command for RedSkyBlock.
    aliases: [is, isle]
    usage: /is [argument/command]
permissions:
  skyblock.*:
    default: op
    children:
      skyblock.is:
      skyblock.create:
      skyblock.tp:
      skyblock.members:
      skyblock.bypass:
      skyblock.kick:
      skyblock.lock:
      skyblock.setworld:
